[flow]

name = "Example Flow"
author = "amin@dorost.nl"


[[container]]
    name = "container-block"
    type = "normal"
    id = "1"
    first = "2"
    last = "3"
    [container.params]
         param-1 = "value-1"


[[action]]
    name = "action-1"
    type = "log"
    id = "2"
    next = ["3"]
    [action.params]
     param-2 = "value-2"




[[action]]
    name = "action-2"
    type = "constant"
    id = "3"
    next = ["4"]
    [action.params]
        const = "branch-2"



[[branch]]
    name = "branch-1"
    type = "normal"
    id = "4"
    [branch.params]
        var-name = "value"
    [branch.mapping]
        branch-1  = "5"
        branch-2 = "6"
        branch-3 = "7"

[[action]]
    name = "action-3"
    type = "log"
    id = "5"
    next = ["7"]
    [action.params]
        param-4 = "value-4"



[[action]]
    name = "Branch eventually came here!"
    type = "log"
    id = "6"
    next = ["8"]
    [action.params]
        "param-5" = "value-5"


[[action]]
    name = "action-5"
    type = "log"
    id = "7"
    [action.params]
        param-6 = "value-6"

[[action]]
    name = "Inputting the JSON"
    type = "json-in"
    id = "8"
    next = ["9"]
    [action.params]
        value = """{
                       "glossary": {
                           "title": "example glossary",
                   		"GlossDiv": {
                               "title": "S",
                   			"GlossList": {
                                   "GlossEntry": {
                                       "ID": "SGML",
                   					"SortAs": "SGML",
                   					"GlossTerm": "Standard Generalized Markup Language",
                   					"Acronym": "SGML",
                   					"Abbrev": "ISO 8879:1986",
                   					"GlossDef": {
                                           "para": "A meta-markup language, used to create markup languages such as DocBook.",
                   						"GlossSeeAlso": ["GML", "XML"]
                                       },
                   					"GlossSee": "markup"
                                   }
                               }
                           }
                       }
                   }"""

[[action]]
    name = "Make post Request"
    type = "http-post"
    id = "9"
    next = ["11"]
    [action.params]
        url = "https://postman-echo.com/post"


[[action]]
    name = "Show the response!"
    type = "log"
    id = "11"